name: Bangun 11 Sony MSM8956 Kernel (Kugo) with GCC 4.9

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev make ccache gdb dwarves git-lfs gnupg curl lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot build-essential \
          libncurses5-dev wget unzip


    - name: Install python2
      run: |
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        sudo ./configure --enable-optimizations
        sudo make altinstall
        sudo ln -s "/usr/local/bin/python2.7" "/usr/bin/python2"
        

    - name: Clone Kernel Source
      run: |
        git clone --depth=1 https://github.com/sonyxperiadev/kernel-copyleft -b 34.4.B.0.xxx kernel

    - name: Download GCC 4.9 Toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/latest-4/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz -O gcc49.tar.xz
        tar -xf gcc49.tar.xz
        mv gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu toolchains
        cd toolchains
        ls -ln
        ls -la bin
        echo "Toolchain extracted to ~/toolchains"
        mkdir -p $GITHUB_WORKSPACE/out
        

    - name: Setup Kernel Config
      run: |
        cd kernel
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        echo "export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig'
        export ARCH=arm64
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=1
        export HOSTCC=gcc
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld 
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        unset CC
        unset CLANG_TRIPLE
        git clean -xfd
        make mrproper
        
        make ARCH=arm64 O=$GITHUB_WORKSPACE/out defconfig

        ls -l $GITHUB_WORKSPACE/out/.config

        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_KERNEL
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_KALLSYMS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_FRAME_POINTER
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_STRIP_ASM_SYMS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_INFO
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_RANDOMIZE_BASE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_GDB_SCRIPTS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_MAGIC_SYSRQ
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_KASAN
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_KASAN_INLINE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_KASAN_OUTLINE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_SERIAL_AMBA_PL011
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_SERIAL_AMBA_PL011_CONSOLE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ARM_GIC_V3
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_MMIO
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_BLK_DEV_INITRD
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEVTMPFS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_TMPFS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_EARLY_PRINTK
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_LL
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_MSM_SERIAL_DEBUGGER
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEVTMPFS_MOUNT 
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_PRINTK
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_SERIAL_CORE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_SERIAL_CORE_CONSOLE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_PLAT_VERSATILE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_SCHED_HMP
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_MENU
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_BLK
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_NET
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_VIRTIO_CONSOLE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_SERIAL_8250
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_SERIAL_8250_CONSOLE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_GOLDFISH
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ANDROID
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ANDROID_BINDER_IPC
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ANDROID_BINDERFS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_OPTIMIZE_FOR_SIZE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ARCH_VIRT
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_ARM64_VA_BITS_48
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_PCI_HOST_GENERIC
        scripts/config --file $GITHUB_WORKSPACE/out/.config --set-val CONFIG_DEBUG_UART_PHYS 0x09000000
        scripts/config --file $GITHUB_WORKSPACE/out/.config --set-val CONFIG_DEBUG_UART_VIRT 0x09000000
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_UART_PL011
        scripts/config --file $GITHUB_WORKSPACE/out/.config --set-val CONFIG_CONSOLE_LOGLEVEL_DEFAULT 7
        scripts/config --file $GITHUB_WORKSPACE/out/.config --set-str CONFIG_CMDLINE "console=ttyAMA0,115200 earlyprintk"
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_CMDLINE_FORCE
        scripts/config --file $GITHUB_WORKSPACE/out/.config --set-val CONFIG_DEBUG_UART_CLOCK 24000000
        
        make ARCH=arm64  O=$GITHUB_WORKSPACE/out olddefconfig

    - name: Build Kernel
      run: |
        cd kernel
        export ARCH=arm64
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=0
        echo "export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig"
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        export HOSTCC=gcc
        export HOSTLDFLAGS="-fcommon"
        export DTC_FLAGS="-f"
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld
        export CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export CLANG_TRIPLE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        echo "===Path Rumah: ===" && echo $HOME
        ls -la $HOME
        echo "===Path workspace: ===" && echo $GITHUB_WORKSPACE 
        ls -la $GITHUB_WORKSPACE 
        echo "===isi folder toolchains==="
        ls -la $GITHUB_WORKSPACE/toolchains 
        echo "===Daftar Environment==="
        env
        echo "===)Cek GCC di folder toolchains==="
        ls -l $GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-gcc
        echo "===cek which gcc==="
        which gcc
        echo "===cek versi gcc==="
        gcc -v
        echo "===cek which gcc android==="
        which aarch64-linux-gnu-gcc
        echo "===cek versi gcc android==="
        $CROSS_COMPILE"gcc" -v
        which clang || echo "clang not found" 
        echo "make mrproper"
        make O=$GITHUB_WORKSPACE/out Image ARCH=arm64 CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu- CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-gcc HOSTCC=/usr/bin/gcc HOSTCXX=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-g++ HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon" -j$(nproc) V=0 2>&1 | tee build.log

    - name: Debug output
      run: |
        echo "Current path: $PWD"
        find $GITHUB_WORKSPACE/kernel/arch/arm64/boot -type f
        ls -lh $GITHUB_WORKSPACE/kernel/arch/arm64/boot/
        ls -lh $GITHUB_WORKSPACE/kernel/
        ls -lh $GITHUB_WORKSPACE/kernel/
        ls -lh $GITHUB_WORKSPACE/out/


    - name: Upload Build Log
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-log
        path: kernel/build.log


    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-output
        path: |
          out/arch/arm64/boot/Image
          out/arch/arm64/boot/Image*
          out/System.map
          out/vmlinux
          out/.config
          out/*.ko
          out/**/*.ko
          out/**/*.dtb*





