name: Bangun 13 Sony MSM8956 Kernel (Kugo) with GCC 4.9

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev make ccache gdb dwarves git-lfs gnupg curl lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot build-essential \
          libncurses5-dev wget unzip sed


    - name: Install python2
      run: |
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        sudo ./configure --enable-optimizations
        sudo make altinstall
        sudo ln -s "/usr/local/bin/python2.7" "/usr/bin/python2"
        

    - name: Clone Kernel Source
      run: |
        git clone --depth=1 https://github.com/sonyxperiadev/kernel-copyleft -b 34.4.B.0.xxx kernel 
        sed -i 's/IRQCHIP_DECLARE(msm_qgic2, "qcom,msm-qgic2", msm_gic_of_init);/IRQCHIP_DECLARE(gic_400, "arm,gic-400", gic_of_init);/g' $GITHUB_WORKSPACE/kernel/drivers/irqchip/irq-gic.c 
        grep -A 2 "IRQCHIP_DECLARE" $GITHUB_WORKSPACE/kernel/drivers/irqchip/irq-gic.c | grep -i "gic-400"

    - name: Download GCC 4.9 Toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/latest-4/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz -O gcc49.tar.xz
        tar -xf gcc49.tar.xz
        mv gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu toolchains
        cd toolchains
        echo "Toolchain extracted to ~/toolchains"
        mkdir -p $GITHUB_WORKSPACE/out
        wget https://github.com/alxtmvn/kugo/raw/refs/heads/main/baru2-new_defconfig -O $GITHUB_WORKSPACE/kernel/arch/arm64/configs/baru2-new_defconfig
        

    - name: Setup Kernel Config
      run: |
        cd kernel
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        echo "export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig"
        export ARCH=arm64
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=1
        export HOSTCC=gcc
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld 
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        export KCFLAGS="-Wno-maybe-uninitialized"
        unset CC
        unset CLANG_TRIPLE

        make ARCH=arm64 O=$GITHUB_WORKSPACE/out baru2-new_defconfig && cp $GITHUB_WORKSPACE/out/.config $GITHUB_WORKSPACE

    - name: Build Kernel
      run: |
        cd kernel
        export ARCH=arm64
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=1
        echo "export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig"
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        export HOSTCC=gcc
        export HOSTLDFLAGS="-fcommon"
        export DTC_FLAGS="-f"
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld
        export CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export CLANG_TRIPLE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-

        make O=$GITHUB_WORKSPACE/out Image ARCH=arm64 CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu- CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-gcc HOSTCC=/usr/bin/gcc HOSTCXX=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-g++ HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon" KCFLAGS=-Wno-error=implicit-function-declaration -j$(nproc) V=0 2>&1 | tee build.log


    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-output
        path: |
          out/arch/arm64/boot/Image
          out/arch/arm64/boot/Image*
          out/System.map
          out/vmlinux
          out/.config
          out/build.log
          kernel/.config
          kernel/build.log 
          $GITHUB_WORKSPACE/.config
          out/*.ko
          out/**/*.ko
          out/**/*.dtb*






