name: Bangun 8 Sony MSM8956 Kernel (Kugo) with GCC 4.9

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev make ccache gdb dwarves git-lfs gnupg curl lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot build-essential \
          libncurses5-dev wget unzip


    - name: Install python2
      run: |
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        sudo ./configure --enable-optimizations
        sudo make altinstall
        sudo ln -s "/usr/local/bin/python2.7" "/usr/bin/python2"
        

    - name: Clone Kernel Source
      run: |
        git clone --depth=1 https://github.com/sonyxperiadev/kernel-copyleft -b 34.4.B.0.xxx kernel

    - name: Download GCC 4.9 Toolchain
      run: |
        wget https://releases.linaro.org/components/toolchain/binaries/latest-4/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz -O gcc49.tar.xz
        tar -xf gcc49.tar.xz
        mv gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu toolchains
        cd toolchains
        ls -ln
        ls -la bin
        echo "Toolchain extracted to ~/toolchains"
        mkdir -p $GITHUB_WORKSPACE/out
        

    - name: Setup Kernel Config
      run: |
        cd kernel
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig
        export ARCH=arm64
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=1
        export HOSTCC=gcc
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld 
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        unset CC
        unset CLANG_TRIPLE
        git clean -xfd
        make mrproper
        
        make O=$GITHUB_WORKSPACE/out msm-perf_defconfig

        ls -l $GITHUB_WORKSPACE/out/.config

        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_KERNEL
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_KALLSYMS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_FRAME_POINTER
        scripts/config --file $GITHUB_WORKSPACE/out/.config --disable CONFIG_STRIP_ASM_SYMS
        scripts/config --file $GITHUB_WORKSPACE/out/.config --enable CONFIG_DEBUG_INFO
        make O=$GITHUB_WORKSPACE/out olddefconfig

    - name: Build Kernel
      run: |
        cd kernel
        export ARCH=arm64
        export PATH=$GITHUB_WORKSPACE/toolchains/bin:$PATH
        export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export USE_HOST_LEX=0
        export KBUILD_DIFFCONFIG=kugo_dcm_diffconfig
        export KBUILD_OUTPUT=$GITHUB_WORKSPACE/out
        export HOSTCC=gcc
        export HOSTLDFLAGS="-fcommon"
        export LD=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-ld
        export CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        export CLANG_TRIPLE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-
        echo "===Path Rumah: ===" && echo $HOME
        ls -la $HOME
        echo "===Path workspace: ===" && echo $GITHUB_WORKSPACE 
        ls -la $GITHUB_WORKSPACE 
        echo "===isi folder toolchains==="
        ls -la $GITHUB_WORKSPACE/toolchains 
        echo "===Daftar Environment==="
        env
        echo "===)Cek GCC di folder toolchains==="
        ls -l $GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-gcc
        echo "===cek which gcc==="
        which gcc
        echo "===cek versi gcc==="
        gcc -v
        echo "===cek which gcc android==="
        which aarch64-linux-gnu-gcc
        echo "===cek versi gcc android==="
        $CROSS_COMPILE"gcc" -v
        which clang || echo "clang not found" 
        echo "make mrproper"
        make O=$GITHUB_WORKSPACE/out Image ARCH=arm64 CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu- CC=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-gcc HOSTCC=/usr/bin/gcc HOSTCXX=$GITHUB_WORKSPACE/toolchains/bin/aarch64-linux-gnu-g++ HOSTCFLAGS="-fcommon" HOSTLDFLAGS="-fcommon" -j$(nproc) V=0 2>&1 | tee build.log

    - name: Debug output
      run: |
        echo "Current path: $PWD"
        find $GITHUB_WORKSPACE/kernel/arch/arm64/boot -type f
        ls -lh $GITHUB_WORKSPACE/kernel/arch/arm64/boot/
        ls -lh $GITHUB_WORKSPACE/kernel/
        ls -lh $GITHUB_WORKSPACE/kernel/
        ls -lh $GITHUB_WORKSPACE/out/


    - name: Upload Build Log
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-log
        path: kernel/build.log


    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-output
        path: |
          kernel/arch/arm64/boot/Image*
          kernel/System.map
          kernel/out/arch/arm64/boot/Image*
          kernel/out/System.map
          kernel/vmlinux
          kernel/out/vmlinux
          kernel/*.ko
          kernel/**/*.ko
          kernel/**/*.dtb* 
          out/



